### ISSUE TITLE
The version in the chrome app store is outdated

### ISSUE THREAD

**Issue by yasith** [Skamaniak/TodoistChromeExtension#17]
Hi,
I noticed that the version in the chrome app store is outdated. Is it possible to get a fresh version up there?

Thank you!

**Comment by Skamaniak** [comment]
Hey @yasith, the only thing that is currently missing in the store version is the possibility to specify the Jira issue key as a placeholder in the todo title. Is that what are you want?
If so, I can release it in a few days. I was waiting for more improvements to pile up but so far I run out of ideas.
If you have any suggestion for an improvement I'm all ears.

**Comment by yasith** [comment]
@Skamaniak haha yeah, I'm after the Jira key :) 

The other one I was looking at was https://github.com/Skamaniak/TodoistChromeExtension/issues/11

Thanks again for making this extension, it's very useful for me.

**Comment by Skamaniak** [comment]
Thank you @yasith, I have found a bit of time and so I added the possibility to preselect the project in the plugin options. It is nothing fancy (no tool -> project mapping as of yet), but it's at least something :).
I also uploaded the new version including the Jira key placeholder. The ball is now on Google's side as they need to approve the package before publishing. Please be patient, the plugin needs quite broad permissions to be able to create the Todoist task from any site and so it usually takes them a bit longer to check and approve. If everything goes smoothly, it should be available in a week or so.

Thank you for using the plugin. It warms my heart hearing that it helps other people too!

**Comment by yasith** [comment]
@Skamaniak  thank you for pushing the update. The plugin is updated on the chrome app store.

This is going to be very helpful for me. Thank you so much.

**Comment by Skamaniak** [comment]
@yasith Awesome, you are right. They were lightning quick this time.
Enjoy!
